In [91]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [92]:
torch.set_default_dtype(torch.float64)

In [105]:
class PUpsample(nn.Module):
    def __init__(self, scale_factor):
        super(PUpsample, self).__init__()
        self.scale_factor = scale_factor

    def forward(self, x, shifts):
        print(x.shape)
        output = torch.repeat_interleave(x, self.scale_factor)
        print(output.shape)
        output = output[(torch.arange(len(output))[None, :] - shifts) % len(output)]
        print(output.shape)
        return output

In [106]:
x = torch.from_numpy(np.random.random((3, 2, 4)))
shifts = torch.from_numpy(np.random.randint(0, 2, size = (3, 1)))

In [107]:
x, shifts

(tensor([[[0.1390, 0.6831, 0.7426, 0.0617],
          [0.9107, 0.6000, 0.1101, 0.9481]],
 
         [[0.0712, 0.1865, 0.0955, 0.4846],
          [0.4249, 0.5007, 0.0622, 0.2640]],
 
         [[0.1484, 0.5101, 0.4747, 0.0871],
          [0.1806, 0.2707, 0.1077, 0.1910]]]),
 tensor([[1],
         [0],
         [0]], dtype=torch.int32))

In [108]:
model = PUpsample(2)

In [109]:
output_x = model(x, shifts)

torch.Size([3, 2, 4])
torch.Size([48])
torch.Size([3, 48])


In [110]:
output_x

tensor([[0.1910, 0.1390, 0.1390, 0.6831, 0.6831, 0.7426, 0.7426, 0.0617, 0.0617,
         0.9107, 0.9107, 0.6000, 0.6000, 0.1101, 0.1101, 0.9481, 0.9481, 0.0712,
         0.0712, 0.1865, 0.1865, 0.0955, 0.0955, 0.4846, 0.4846, 0.4249, 0.4249,
         0.5007, 0.5007, 0.0622, 0.0622, 0.2640, 0.2640, 0.1484, 0.1484, 0.5101,
         0.5101, 0.4747, 0.4747, 0.0871, 0.0871, 0.1806, 0.1806, 0.2707, 0.2707,
         0.1077, 0.1077, 0.1910],
        [0.1390, 0.1390, 0.6831, 0.6831, 0.7426, 0.7426, 0.0617, 0.0617, 0.9107,
         0.9107, 0.6000, 0.6000, 0.1101, 0.1101, 0.9481, 0.9481, 0.0712, 0.0712,
         0.1865, 0.1865, 0.0955, 0.0955, 0.4846, 0.4846, 0.4249, 0.4249, 0.5007,
         0.5007, 0.0622, 0.0622, 0.2640, 0.2640, 0.1484, 0.1484, 0.5101, 0.5101,
         0.4747, 0.4747, 0.0871, 0.0871, 0.1806, 0.1806, 0.2707, 0.2707, 0.1077,
         0.1077, 0.1910, 0.1910],
        [0.1390, 0.1390, 0.6831, 0.6831, 0.7426, 0.7426, 0.0617, 0.0617, 0.9107,
         0.9107, 0.6000, 0.6000, 0.1101, 