In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.set_default_dtype(torch.float64)

In [3]:
class PConv1d(nn.Module):
    def __init__(self, in_channels, out_channels, padding):
        super(PConv1d, self).__init__()

        self.padding = (padding, padding)
        self.conv1d = nn.Conv1d(in_channels, out_channels, 2*padding+1)

    def forward(self, x):
        output = F.pad(x, self.padding, mode = 'circular')
        output = self.conv1d(output)
        return output

In [4]:
x = torch.from_numpy(np.random.random((3, 2, 6)))

In [5]:
x

tensor([[[0.4601, 0.1074, 0.5794, 0.2621, 0.6896, 0.1012],
         [0.4903, 0.8811, 0.3268, 0.9351, 0.1016, 0.0076]],

        [[0.7071, 0.9346, 0.9202, 0.8002, 0.2073, 0.6473],
         [0.2030, 0.9389, 0.8626, 0.9349, 0.7082, 0.0626]],

        [[0.9739, 0.1031, 0.5058, 0.9502, 0.6955, 0.1554],
         [0.2333, 0.5877, 0.6750, 0.7439, 0.5143, 0.6285]]])

In [6]:
model = PConv1d(2, 2, 2)

In [7]:
output_x = model(x)

In [8]:
y = torch.roll(x, 3, dims = -1)

In [9]:
y

tensor([[[0.2621, 0.6896, 0.1012, 0.4601, 0.1074, 0.5794],
         [0.9351, 0.1016, 0.0076, 0.4903, 0.8811, 0.3268]],

        [[0.8002, 0.2073, 0.6473, 0.7071, 0.9346, 0.9202],
         [0.9349, 0.7082, 0.0626, 0.2030, 0.9389, 0.8626]],

        [[0.9502, 0.6955, 0.1554, 0.9739, 0.1031, 0.5058],
         [0.7439, 0.5143, 0.6285, 0.2333, 0.5877, 0.6750]]])

In [10]:
output_y = model(y)

In [11]:
output_x - torch.roll(output_y, -3, dims = -1)

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]], grad_fn=<SubBackward0>)